import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import {Outfit, Manrope, Wix_Madefor_Display, Lato} from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

const open = Manrope({
  subsets:['latin'],
})

const roboto = Lato({
  subsets:['latin'],
  weight:["100", "300", "400", "700", "900"]
})

export const metadata: Metadata = {
  title: 'Doc-Note',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
  
      <body className={open.className}>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
