import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import {Outfit, Montserrat, Wix_Madefor_Display} from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

const wix = Wix_Madefor_Display({
  subsets:['latin'],
})

const montse = Montserrat({
  subsets:['latin'],
})

export const metadata: Metadata = {
  title: 'Doc-Note',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
  
      <body className={wix.className}>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
